const uuid = require('uuid').v4;
/**
 * Class to create a new task
 */
class Task {
  /**
   * New task details
   * @param {Object} [taskInfo] - Task information
   * @param {String} [taskInfo.id=uuid()] - Autogenerated task uuid
   * @param {String} [taskInfo.title=TEST_TASK] - Provided task title
   * @param {Number} [taskInfo.order=0] - Provided task order
   * @param {String} [taskInfo.description=DESC] - Provided task description
   * @param {String} [taskInfo.userId] - Provided task assignee Id
   * @param {String} [taskInfo.boardId] - Provided task board Id
   * @param {String} [taskInfo.columnId] - Provided task column Id
   */
  constructor({
    id = uuid(),
    title = 'TEST_TASK',
    order = 0,
    description = 'TEST_DESC',
    userId = '',
    boardId = '',
    columnId = '',
  } = {}) {
    /** @property {String} id - autogenerated task id */
    this.id = id;
    /** @property {String} title - task title */
    this.title = title;
    /** @property {Number} order - task order */
    this.order = order;
    /** @property {String} description - task decsription */
    this.description = description;
    /** @property {String} userId - task assignee */
    this.userId = userId;
    /** @property {String} boardId - task board Id */
    this.boardId = boardId;
    /** @property {String} columnId - task column Id */
    this.columnId = columnId;
  }

 /**
   * @property {Function} toResponse Returns task instance
   * @param {Task} user a User class instance
   * @returns {Task} User class object with trimmed password
   */
  static toResponse(task) {
    const { id, title, order, description, userId, boardId, columnId } = task;
    return { id, title, order, description, userId, boardId, columnId };
  }
}
module.exports = Task;
