version: '3.5'
services:
  node:
    build: .
    image: petrgali/rest-api
    restart: always
    working_dir: /app/src
    networks:
      - rs-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app/src
  postgres:
    build: ./database/
    image: petrgali/postgres
    restart: always
    networks:
      - rs-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
networks:
  rs-network:
    name: custom-network
    driver: bridge
