version: '3.5'
services:
  node:
    build: .
    image: petrgali/rest-api
    restart: on-failure
    networks:
      - rs-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./logs/:/app/logs
      - ./src/:/app/src
    environment:
      - PORT=${PORT}
  postgres:
    build: ./database/
    image: petrgali/postgres
    restart: on-failure
    networks:
      - rs-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
networks:
  rs-network:
    name: custom-network
    driver: bridge
volumes:
  postgres:
    name: postgresDB