version: '3.5'
services:
  node:
    build: .
    image: petrgali/rest-api
    restart: on-failure
    networks:
      - rs-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./logs/:/app/logs
      - ./src/:/app/src
    environment:
      PORT: ${PORT}
  postgres:
    build: ./database/
    image: petrgali/postgres
    restart: on-failure
    networks:
      - rs-network
      - test-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    depends_on:
      - node
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    ports:
      - '8080:80'
    environment:
      PGADMIN_PORT: ${PGADMIN_PORT}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - test-network
networks:
  rs-network:
    name: custom-network
    driver: bridge
  test-network:
    name: db-network
    driver: bridge
volumes:
  pgdata:
    name: postgresDB