const uuid = require('uuid').v4;

export interface IColumn {
  id: string,
  title: string,
  order: number
}
export interface IColumnRaw {
  title: string,
  order: number
}
/**
 * Class to create a new column
 */
class Column {
  public id: string;
  public title: string;
  public order: number
  /**
   * New column details
   * @param {Object} [columnInfo={}] - Task information
   * @param {String} [columnInfo.id=uuid()] - Autogenerated task uuid
   * @param {String} [columnInfo.title=TEST_COLUMN] - Provided task title
   * @param {Number} [columnInfo.order=0] - Provided task order
   */
  constructor({ id = uuid(), title = 'TEST_COLUMN', order = 0 } = {}) {
    /** @property {String} id - column autogenerated id */
    this.id = id;
    /** @property {String} title - column title */
    this.title = title;
    /** @property {Number} order - column order */
    this.order = order;
  }
}

module.exports = Column;
