const uuid = require('uuid').v4;
/**
 * Class to create a new column
 */
class Column {
  /**
   * New column details
   * @param {Object} [columnInfo] - Task information
   * @param {String} [columnInfo.id=uuid()] - Autogenerated task uuid
   * @param {String} [columnInfo.title=TEST_COLUMN] - Provided task title
   * @param {Number} [columnInfo.order=0] - Provided task order
   */
  constructor({ id = uuid(), title = 'TEST_COLUMN', order = 0 } = {}) {
    /** @property {String} id - column autogenerated id */
    this.id = id;
    /** @property {String} title - column title */
    this.title = title;
    /** @property {String} order - column order */
    this.order = order;
  }
}

module.exports = Column;
