import { IColumn } from '../columns/columns.model'
const uuid = require('uuid').v4;

export interface IBoard {
  id: string,
  title: string,
  columns: Array<IColumn>
}
export interface IBoardRaw {
  title?: string,
  columns?: Array<IColumn>
}
/**
 * Class to create a new board
 */
class Board {
  public id: string;
  public title: string;
  public columns: Array<IColumn>;
  /**
   * New board details
   * @param {Object} [boardInfo={}] - board information
   * @param {String} [boardInfo.id=uuid()] - Autogenerated board uuid
   * @param {String} [boardInfo.title=TEST_BOARD] - Provided board title
   * @param {Array<Column>} [boardInfo.columns=[]] - Provided board columns
   */
  constructor({ id = uuid(), title = 'TEST_BOARD', columns = [] } = {}) {
    /** @property {String} id - board autogenerated id */
    this.id = id;
    /** @property {String} title - board title */
    this.title = title;
    /** @property {Array<Column>} columns - list of board columns */
    this.columns = columns;
  }
}
module.exports = Board;
