const uuid = require('uuid').v4;
/**
 * Class to create a new board
 */
class Board {
  /**
   * New board details
   * @param {Object} [boardInfo={}] - board information
   * @param {String} [boardInfo.id=uuid()] - Autogenerated board uuid
   * @param {String} [boardInfo.title=TEST_BOARD] - Provided board title
   * @param {Array<Column>} [boardInfo.columns=[]] - Provided board columns
   */
  constructor({ id = uuid(), title = 'TEST_BOARD', columns = [] } = {}) {
    /** @property {String} id - board autogenerated id */
    this.id = id;
    /** @property {String} title - board title */
    this.title = title;
    /** @property {Array<Column>} columns - list of board columns */
    this.columns = columns;
  }
}
module.exports = Board;
